### ISSUE TITLE
Error :((

### ISSUE THREAD

**Issue by standnguyen197** [MatteoGabriele/vue-speech#1]
`ERROR in static/js/vendor.78a84a0726a1587749c3.js from UglifyJs
Unexpected token: punc ()) [./node_modules/vue-speech/dist/vue-speech.js:151,0][static/js/vendor.78a84a0726a1587749c3.js:8839,9]`

**Comment by MatteoGabriele** [comment]
Hi @standnguyen197 
when does this happen? can you create a small reproduction with vue-cli? thanks a lot

**Comment by MatteoGabriele** [comment]
close for inactivity
