### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: Vue.component is not a function"

### ISSUE THREAD

**Issue by shilik** [MatteoGabriele/vue-speech#2]
Hi, Thanks for creating such a good plugin.
When I followed your instructions step by step to integrate this plugin into my project,
I got an error message [Vue warn]: Error in render: "TypeError: Vue.component is not a function".
Any ideas for getting this problem solved? 
Thank you very much.

shilik

**Comment by MatteoGabriele** [comment]
Hi @shilik could you maybe explain a little bit more about your setup? would be perfect also a little public repo maybe done with vue-cli so that I can have a look. Thanks a lot

**Comment by MatteoGabriele** [comment]
close for inactivity
