### ISSUE TITLE
Not an issue, but a thank you... and some inspiration?

### ISSUE THREAD

**Issue by JamieCurnow** [MatteoGabriele/vue-speech#4]
First up, thanks for making this and giving me some starting blocks! I'm implementing in an app I'm making where I took out some logic from your plugin and made it into a component. I've put it up on codepen with the changes I made using Vuetify to make it look nice.

Includes start/stop button, and sync'ing the text to a parent prop. Hope someone finds it useful 😄 
[https://codepen.io/JamieCurnow/pen/ZoxVQg?editors=1010](https://codepen.io/JamieCurnow/pen/ZoxVQg?editors=1010)

**Comment by MatteoGabriele** [comment]
nice man super cool! I still have to invest little of time in this plugin to make it more usable.
thanks for the suggestions and feedback, always appreciated!
